# Project Name
site_name: MuflihunDev Blog
theme:
  name: material

site_author: MuflihunDev
site_description: >-
  Modul ini digunakan untuk membantu seseorang yang baru saja mulai mempelajari web development
  Dalam modul ini terdapat topik antara lain html, css, js, dan php
  Modul ini disusun bertahap dari materi dasar sampai dengan sedikit advance

repo_name: mufihunaf.github.io/web-dasar